//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQMProjectEvolutionManagerWS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ReleaseProjects = new HashSet<ReleaseProject>();
        }
    
        public int ProjectId { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsActive { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<ReleaseProject> ReleaseProjects { get; set; }
    }
}
