//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQMProjectEvolutionManagerWS.Data
{
    using System;
    using System.Collections.Generic;

    using IQMProjectEvolutionManagerWS.Data.Interfaces.OnTimeModels;

    public partial class Release : IRelease
    {
        public Release()
        {
            this.ReleaseProjects = new HashSet<ReleaseProject>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ReleaseId { get; set; }
        public int ParentReleaseId { get; set; }
        public int ReleaseTypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int ReleaseStatusTypeId { get; set; }
        public string Path { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime VelocityStartDate { get; set; }
        public string ReleaseNotes { get; set; }
    
        public virtual ICollection<ReleaseProject> ReleaseProjects { get; set; }
        public virtual ReleaseType ReleaseType { get; set; }
        public virtual ReleaseStatusType ReleaseStatusType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
