//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQMProjectEvolutionManagerWS.Data
{
    using System;
    using System.Collections.Generic;

    using IQMProjectEvolutionManagerWS.Data.Interfaces.OnTimeModels;

    public partial class Task : ITask
    {
        public Task()
        {
            this.WorkLogs = new HashSet<WorkLog>();
        }
    
        public int TaskId { get; set; }
        public string TaskNumber { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public int CategoryTypeId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsPublic { get; set; }
        public int AssignedToId { get; set; }
        public int ReportedById { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int LastUpdatedById { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool Archived { get; set; }
        public float EstimatedDuration { get; set; }
        public int DurationUnitTypeId { get; set; }
        public float ActualDuration { get; set; }
        public int ActualUnitTypeId { get; set; }
        public int WorkflowStepId { get; set; }
        public int PriorityTypeId { get; set; }
        public float RemainingDuration { get; set; }
        public int RemainingUnitTypeId { get; set; }
        public int ReleaseId { get; set; }
        public int StatusTypeId { get; set; }
        public bool PubliclyViewable { get; set; }
        public int ReportedByCustomerContactId { get; set; }
        public byte PercentComplete { get; set; }
    
        public virtual TimeUnitType ActualTimeUnitType { get; set; }
        public virtual TimeUnitType RemainingTimeUnitType { get; set; }
        public virtual TimeUnitType EstimatedTimeUnitType { get; set; }
        public virtual ICollection<WorkLog> WorkLogs { get; set; }
        public virtual Release Release { get; set; }
        public virtual User User { get; set; }
    }
}
