//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQMProjectEvolutionManagerWS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeUnitType
    {
        public TimeUnitType()
        {
            this.WorkLogs = new HashSet<WorkLog>();
            this.ActualTimeUnitType = new HashSet<Task>();
            this.RemainingTimeUnitType = new HashSet<Task>();
            this.EstimatedTimeUnitType = new HashSet<Task>();
        }
    
        public int TimeUnitTypeId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int DisplayOrder { get; set; }
        public int ConversionFactor { get; set; }
    
        public virtual ICollection<WorkLog> WorkLogs { get; set; }
        public virtual ICollection<Task> ActualTimeUnitType { get; set; }
        public virtual ICollection<Task> RemainingTimeUnitType { get; set; }
        public virtual ICollection<Task> EstimatedTimeUnitType { get; set; }
    }
}
