//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQMProjectEvolutionManagerWS.Data
{
    using System;
    using System.Collections.Generic;

    using IQMProjectEvolutionManagerWS.Data.Interfaces.OnTimeModels;

    public partial class User : IUser
    {
        public User()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string WindowsId { get; set; }
        public bool UseWindowsAuth { get; set; }
        public bool BuiltInAccount { get; set; }
        public string SettingsXml { get; set; }
        public bool IsActive { get; set; }
        public bool UseWindowsClient { get; set; }
        public bool UseWebClient { get; set; }
        public bool UseVSClient { get; set; }
        public bool UseMixedMode { get; set; }
        public int EnterpriseConnectionType { get; set; }
        public bool UseIPhoneClient { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public byte[] ReadMessages { get; set; }
        public byte[] IPhoneSettings { get; set; }
        public bool HasReadUpgradeMessage { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
